#ifndef ROLLING_LOG_BOX_H
#define ROLLING_LOG_BOX_H

#define BOX_LH      "\u2500" //	─	// BOX DRAWINGS LIGHT HORIZONTAL
#define BOX_HH      "\u2501" //	━	// BOX DRAWINGS HEAVY HORIZONTAL
#define BOX_LV      "\u2502" //	│	// BOX DRAWINGS LIGHT VERTICAL
#define BOX_HV      "\u2503" //	┃	// BOX DRAWINGS HEAVY VERTICAL
#define BOX_LTDH    "\u2504" //	┄	// BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
#define BOX_HTDH    "\u2505" //	┅	// BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
#define BOX_LTDV    "\u2506" //	┆	// BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
#define BOX_HTDV    "\u2507" //	┇	// BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
#define BOX_LQDH    "\u2508" //	┈	// BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
#define BOX_HQDH    "\u2509" //	┉	// BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
#define BOX_LQDV    "\u250A" //	┊	// BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
#define BOX_HQDV    "\u250B" //	┋	// BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
#define BOX_LDR     "\u250C" //	┌	// BOX DRAWINGS LIGHT DOWN AND RIGHT
#define BOX_DL_RH   "\u250D" //	┍	// BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
#define BOX_DH_RL   "\u250E" //	┎	// BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
#define BOX_HDR     "\u250F" //	┏	// BOX DRAWINGS HEAVY DOWN AND RIGHT


#define BOX_LDL     "\u2510" //	┐	// BOX DRAWINGS LIGHT DOWN AND LEFT
#define BOX_DL_LH   "\u2511" //	┑	// BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
#define BOX_DH_LL   "\u2512" //	┒	// BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
#define BOX_HDL     "\u2513" //	┓	// BOX DRAWINGS HEAVY DOWN AND LEFT
#define BOX_LUR     "\u2514" //	└	// BOX DRAWINGS LIGHT UP AND RIGHT
#define BOX_UL_RH   "\u2515" //	┕	// BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
#define BOX_UH_RL   "\u2516" //	┖	// BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
#define BOX_HUR     "\u2517" //	┗	// BOX DRAWINGS HEAVY UP AND RIGHT
#define BOX_LUL     "\u2518" //	┘	// BOX DRAWINGS LIGHT UP AND LEFT
#define BOX_UL_LH   "\u2519" //	┙	// BOX DRAWINGS UP LIGHT AND LEFT HEAVY
#define BOX_UH_LL   "\u251A" //	┚	// BOX DRAWINGS UP HEAVY AND LEFT LIGHT
#define BOX_HUL     "\u251B" //	┛	// BOX DRAWINGS HEAVY UP AND LEFT
#define BOX_LVR     "\u251C" //	├	// BOX DRAWINGS LIGHT VERTICAL AND RIGHT
#define BOX_VL_RH   "\u251D" //	┝	// BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY
#define BOX_UH_RDL  "\u251E" //	┞	// BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT
#define BOX_DH_RUL  "\u251F" //	┟	// BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT


#define BOX_VH_RL   "\u2520" //	┠	// BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT
#define BOX_DL_RUH  "\u2521" //	┡	// BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY
#define BOX_UL_RDH  "\u2522" //	┢	// BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY
#define BOX_HVR     "\u2523" //	┣	// BOX DRAWINGS HEAVY VERTICAL AND RIGHT
#define BOX_LVL     "\u2524" //	┤	// BOX DRAWINGS LIGHT VERTICAL AND LEFT
#define BOX_VL_LH   "\u2525" //	┥	// BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY
#define BOX_UH_LDL  "\u2526" //	┦	// BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT
#define BOX_DH_LUL  "\u2527" //	┧	// BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT
#define BOX_VH_LL   "\u2528" //	┨	// BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT
#define BOX_DL_LUH  "\u2529" //	┩	// BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY
#define BOX_UL_LDH  "\u252A" //	┪	// BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY
#define BOX_HVL     "\u252B" //	┫	// BOX DRAWINGS HEAVY VERTICAL AND LEFT
#define BOX_LDH     "\u252C" //	┬	// BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
#define BOX_LH_RDL  "\u252D" //	┭	// BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT
#define BOX_RH_LDL  "\u252E" //	┮	// BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT
#define BOX_DL_HH   "\u252F" //	┯	// BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY


#define BOX_DH_HL   "\u2530" //	┰	// BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT
#define BOX_RL_LDH  "\u2531" //	┱	// BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY
#define BOX_LL_RDH  "\u2532" //	┲	// BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY
#define BOX_HDH     "\u2533" //	┳	// BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
#define BOX_LUH     "\u2534" //	┴	// BOX DRAWINGS LIGHT UP AND HORIZONTAL
#define BOX_LH_RUL  "\u2535" //	┵	// BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT
#define BOX_RH_LUL  "\u2536" //	┶	// BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT
#define BOX_UL_HH   "\u2537" //	┷	// BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY
#define BOX_UH_HL   "\u2538" //	┸	// BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT
#define BOX_RL_LUH  "\u2539" //	┹	// BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY
#define BOX_LL_RUH  "\u253A" //	┺	// BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY
#define BOX_HUH     "\u253B" //	┻	// BOX DRAWINGS HEAVY UP AND HORIZONTAL
#define BOX_LVH     "\u253C" //	┼	// BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
#define BOX_LH_RVL  "\u253D" //	┽	// BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT
#define BOX_RH_LVL  "\u253E" //	┾	// BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT
#define BOX_VL_HH   "\u253F" //	┿	// BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY


#define BOX_UH_DHL  "\u2540" //	╀	// BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT
#define BOX_DH_UHL  "\u2541" //	╁	// BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT
#define BOX_VH_HL   "\u2542" //	╂	// BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT
#define BOX_LUH_RDL "\u2543" //	╃	// BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT
#define BOX_RUH_LDL "\u2544" //	╄	// BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT
#define BOX_LDH_RUL "\u2545" //	╅	// BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT
#define BOX_RDH_LUL "\u2546" //	╆	// BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT
#define BOX_DL_UHH  "\u2547" //	╇	// BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY
#define BOX_UL_DHH  "\u2548" //	╈	// BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY
#define BOX_RL_LVH  "\u2549" //	╉	// BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY
#define BOX_LL_RVH  "\u254A" //	╊	// BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY
#define BOX_HVH     "\u254B" //	╋	// BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
#define BOX_LDDH    "\u254C" //	╌	// BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL
#define BOX_HDDH    "\u254D" //	╍	// BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL
#define BOX_LDDV    "\u254E" //	╎	// BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL
#define BOX_HDDV    "\u254F" //	╏	// BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL


#define BOX_DH      "\u2550" //	═	// BOX DRAWINGS DOUBLE HORIZONTAL
#define BOX_DV      "\u2551" //	║	// BOX DRAWINGS DOUBLE VERTICAL
#define BOX_DS_RD   "\u2552" //	╒	// BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
#define BOX_DD_RS   "\u2553" //	╓	// BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
#define BOX_DDR     "\u2554" //	╔	// BOX DRAWINGS DOUBLE DOWN AND RIGHT
#define BOX_DS_LD   "\u2555" //	╕	// BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
#define BOX_DD_LS   "\u2556" //	╖	// BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
#define BOX_DDL     "\u2557" //	╗	// BOX DRAWINGS DOUBLE DOWN AND LEFT
#define BOX_US_RD   "\u2558" //	╘	// BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
#define BOX_UD_RS   "\u2559" //	╙	// BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
#define BOX_DUR     "\u255A" //	╚	// BOX DRAWINGS DOUBLE UP AND RIGHT
#define BOX_US_LD   "\u255B" //	╛	// BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
#define BOX_UD_LS   "\u255C" //	╜	// BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
#define BOX_DUL     "\u255D" //	╝	// BOX DRAWINGS DOUBLE UP AND LEFT
#define BOX_VS_RD   "\u255E" //	╞	// BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
#define BOX_VD_RS   "\u255F" //	╟	// BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE


#define BOX_DVR     "\u2560" //	╠	// BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
#define BOX_VS_LD   "\u2561" //	╡	// BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
#define BOX_VD_LS   "\u2562" //	╢	// BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
#define BOX_DVL     "\u2563" //	╣	// BOX DRAWINGS DOUBLE VERTICAL AND LEFT
#define BOX_DS_HD   "\u2564" //	╤	// BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
#define BOX_DD_HS   "\u2565" //	╥	// BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
#define BOX_DDH     "\u2566" //	╦	// BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
#define BOX_US_HD   "\u2567" //	╧	// BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
#define BOX_UD_HS   "\u2568" //	╨	// BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
#define BOX_DUH     "\u2569" //	╩	// BOX DRAWINGS DOUBLE UP AND HORIZONTAL
#define BOX_VS_HD   "\u256A" //	╪	// BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
#define BOX_VD_HS   "\u256B" //	╫	// BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
#define BOX_DVH     "\u256C" //	╬	// BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
#define BOX_LADR    "\u256D" //	╭	// BOX DRAWINGS LIGHT ARC DOWN AND RIGHT
#define BOX_LADL    "\u256E" //	╮	// BOX DRAWINGS LIGHT ARC DOWN AND LEFT


#define BOX_LAUL    "\u256F" //	╯	// BOX DRAWINGS LIGHT ARC UP AND LEFT
#define BOX_LAUR    "\u2570" //	╰	// BOX DRAWINGS LIGHT ARC UP AND RIGHT
#define BOX_LDURLL  "\u2571" //	╱	// BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
#define BOX_LDULLR  "\u2572" //	╲	// BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
#define BOX_LDC     "\u2573" //	╳	// BOX DRAWINGS LIGHT DIAGONAL CROSS
#define BOX_LL      "\u2574" //	╴	// BOX DRAWINGS LIGHT LEFT
#define BOX_LU      "\u2575" //	╵	// BOX DRAWINGS LIGHT UP
#define BOX_LR      "\u2576" //	╶	// BOX DRAWINGS LIGHT RIGHT
#define BOX_LD      "\u2577" //	╷	// BOX DRAWINGS LIGHT DOWN
#define BOX_HL      "\u2578" //	╸	// BOX DRAWINGS HEAVY LEFT
#define BOX_HU      "\u2579" //	╹	// BOX DRAWINGS HEAVY UP
#define BOX_HR      "\u257A" //	╺	// BOX DRAWINGS HEAVY RIGHT
#define BOX_HD      "\u257B" //	╻	// BOX DRAWINGS HEAVY DOWN
#define BOX_LL_HR   "\u257C" //	╼	// BOX DRAWINGS LIGHT LEFT AND HEAVY RIGHT
#define BOX_LU_HD   "\u257D" //	╽	// BOX DRAWINGS LIGHT UP AND HEAVY DOWN
#define BOX_HL_LR   "\u257E" //	╾	// BOX DRAWINGS HEAVY LEFT AND LIGHT RIGHT
#define BOX_HU_LD   "\u257F" //	╿	// BOX DRAWINGS HEAVY UP AND LIGHT DOWN

#endif //ROLLING_LOG_BOX_H
